### ISSUE TITLE
Font Awesome: conflicts causing rendering issues

### ISSUE THREAD

**Issue by matt-d-webb** [mliebelt/PgnViewerJS#226]
First of all, great project! ♟️

**Issue:**

I am running into a rendering issue which I believe relates to a font-awesome conflict, possibly because I am using a [pro kit](https://fontawesome.com/kits) which I think is v6 based.

When I am not loading this kit (via CDN), I can render the following viewer, with some [custom css overrides](https://github.com/chess-centre/platform/blob/master/chess-centre-app/src/assets/css/additional-styles/chessboard.scss):

![image](https://user-images.githubusercontent.com/36933715/118194876-08002300-b442-11eb-9e48-ee597e577f2f.png)

Then once I have my font-awesome kit script added to my index.html [like so](https://github.com/chess-centre/platform/blob/master/chess-centre-app/public/index.html#L88), I get the following: 

```
  <body>
    <div id="root"></div>
  </body>
  <script defer src="https://kit.fontawesome.com/3af9f0f4d1.js" crossorigin="anonymous"></script>
```

**Render result** - note, the move click events also do not work / attach:

![image](https://user-images.githubusercontent.com/36933715/118195179-a2606680-b442-11eb-8e3c-8e27923b30bb.png)

**Resolution**

I have _attempted_ to fork the repo and toy around with the [hard-copy dependency](https://github.com/mliebelt/PgnViewerJS/tree/master/modules/pgn-viewer/src/fontawesome) of font-awesome v5 you have but, struggled to get the build working following the instructions. My assumption would be, I could remove your internal version entirely, relying solely on my project loading this dependency in the header. But this would be a terrible hack! 🤣

Happy to _try_ to collaborate on this as this would be especially valuble to my application. But any short-term workarounds or suggestions would be warmly received.

**Comment by mliebelt** [comment]
I yesterday fixed a problem when using the PgnViewerJS as part of [PgnViewerJS-WP](https://github.com/mliebelt/PgnViewerJS-WP), a variant for Wordpress. See the ticket #225 and my fix there.

The screenshot you show me was similar to the one I got. Could you try if the new version 1.5.3 fixes the problem for you, or if the version is the reason for the problem. There, I had some rules that matched the class `.button` (which is a common name). So I had to change that class to something new (chosen `.pgnvbutton`).

----

Ok, looked at yout [fork](https://github.com/chess-centre/PgnViewerJS), and you have the current version. Your custom CSS has to be changed then to that new rule, so change `div.buttons > i.button` to `div.buttons > i.pgnvbutton`. I hope that fixes the issue for you.

What was the "instructions you were following for the build"? With a fork, the following should work all the time:

1. You should be in the root directory of the project.
2. `npm install`
3. `cd modules/pgn-viewer`
4. `npm install` again.

You will then find in the directory `modules/pgn-viewer/lib` the new built javascript library, uncompressed and compressed.

I hope you can fix your problem with that, but possibly using 2 different versions of Fontawesome is not so easy to fix. I could at least redruce the icons to only the ones that are needed for my library, but that would be a different topic then.

**Comment by matt-d-webb** [comment]
Unfortunately, testing this locally this hasn't resolved the issue.

I've tried to vary the order of load or when I import the custom css for the board etc, but these seem not to make any difference.

Trying to think of other possible solutions  ... 🤔

**Comment by mliebelt** [comment]
What do I have to do to reproduce the problem myself? Am I able to clone your repo, build the application and start and use it then? Are there examples / test cases available, that can be used without being the maintainer of the repo? Did you had that problem from beginning, or arose that only after migrating to the latest version? If yes, which version did you use before?

**Comment by mliebelt** [comment]
I was able to recreate your problem on the branch fa-226

![image](https://user-images.githubusercontent.com/520039/118597989-be029e80-b7ad-11eb-8ffa-209d318e0220.png)

The developer tools of Chrome show me then the following

![image](https://user-images.githubusercontent.com/520039/118598087-e12d4e00-b7ad-11eb-9cfb-f0ed7c30cf3c.png)

When I switch off the loading of Fontawesome from CDN, I see the following code

![image](https://user-images.githubusercontent.com/520039/118598278-1b96eb00-b7ae-11eb-945d-1d00369839f1.png)

Adding the following lines to the CSS

```
.pgnvjs div.buttons > i.pgnvbutton, .pgnvjs div.edit > i.pgnvbutton,
.pgnvjs div.buttons > svg.pgnvbutton, .pgnvjs div.edit > svg.pgnvbutton
```
fixed the problem (kind of, looks ugly, there seem to be differences between svg display and the option I use.

![image](https://user-images.githubusercontent.com/520039/118599179-6fee9a80-b7af-11eb-9029-99849cf074ec.png)

Here is the bounding box of 1 icon

![image](https://user-images.githubusercontent.com/520039/118599250-87c61e80-b7af-11eb-837d-e960e4d31db6.png)

I will check if there is a workaround for this, and try to fix it, but I think we have found the reason why using Fontawesome from CDN breaks the CSS. Perhaps you can do a fix for yourself in your custom CSS.

**Comment by matt-d-webb** [comment]
Wow, thank you for the detailed follow up. I hadn't had chance to really delve into the issue as our site only went live at the weekend so classically fixing bugs. :-)

You're correct, using the svg selector I can update the css and should be able to tweak this to get the desired style - thank you.
I did however note that the click events on the buttons still don't work, haven't had an opportunity to see why as yet.

As you pin pointed the issue in the css (svg !== i) I realised I can switch my custom font-awesome kit to use "web font" instead of "svg", this resolves all the issues 🎉

![image](https://user-images.githubusercontent.com/36933715/118633118-0b403980-b7c9-11eb-8b39-3e853a468ea3.png)

Would be happy to close the issue but you may well want to iterate on the click events if a similar issue arises.

**Comment by mliebelt** [comment]
Thank you for your feedback. yes, I will take the chance to see if if could work with Fontawesome SVG icons as well. The behavior with the click events is strange. So you could easily fix it by switching (for the moment) to Web Font, perhaps later, you may switch back to SVG (if and when the problem is solved).

**Comment by matt-d-webb** [comment]
Yes, I'd certainly switch back to SVG.

I will take a deeper look myself soon to see if I can understand why these events are seemingly detached. I've a few other production bugs to release for my app before hand, then I can spend some time on this! I've a big section within the site which will cater exclusively for "previous games" so want this to work as seemlessly as possible as it will really add value to the whole experience.

Lastly, you can actually create an account on [chesscentre.online](https://www.chesscentre.online/register) (it's completely free! 🔥) only paid memberships are for those who phyically come to our club (in the UK) to participate in individual competitions / team league matches, congresses & club nights ♟️🤩

**Comment by mliebelt** [comment]
I checked again, and I think that the layout of the button bar (not the buttons themselves) are different in Fontawesome 5 and Fontawesome 6. At the moment, I see with identical code and CSS different bounding boxes.

Original, with Fontawesome 5, Font based icons
![image](https://user-images.githubusercontent.com/520039/118802301-42364e00-b8a2-11eb-9d77-7b011f59f5e1.png)

Branch with Fontawesome 5, Font based icons, loaded from CDN
![image](https://user-images.githubusercontent.com/520039/118802510-7dd11800-b8a2-11eb-80a4-4965a5e3ec0b.png)

**Comment by mliebelt** [comment]
Fixed the 2 things, but I have to create a new patch version so it could be used by others.

**Comment by mliebelt** [comment]
Published version 1.5.4 of pgn-viewer, by using that version in https://github.com/chess-centre/platform/blob/master/chess-centre-app/package.json you should be able to switch again to SVG. I have not seen any difference in using SVG or Web Font.
